worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  www.goulielmos.org;
        include paths.conf
    }

    # we also have goulielmos.org which forwards to https://localhost
    # it requires the "Origin Server Name" setting to be "agouliel.ddns.net"
    # this setting tells the tunnel:
    # "Even though the user typed goulielmos.org in their browser,
    # when you connect to the Mac mini, tell Nginx that you are looking for agouliel.ddns.net."
    # This "tricks" Nginx into matching the request to the existing HTTPS server block.
    # Nginx is configured with ssl_certificate fullchain.pem which is tied to the agouliel.ddns.net domain.

    server {
        listen       80;
        server_name  agouliel.ddns.net;
        location / {
          # redirect any requests to the same URL but on https
          return 301 https://$host$request_uri;
        }
        # redirect server error pages to the static page /50x.html
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }

    # HTTPS server
    server {
        listen       443 ssl;
        server_name  agouliel.ddns.net;
        ssl_certificate      fullchain.pem;
        ssl_certificate_key  key.pem;
        include paths.conf
        client_max_body_size 20M;
    }

    include servers/*;
}
