# this file needs to be symlinked like nginx.conf
# cd /opt/homebrew/etc/nginx
# ln -s /opt/homebrew/var/www/paths.conf paths.conf

# ---------- MICROBLOG -----------

# https://stackoverflow.com/questions/53207059/react-nginx-routing-to-subdirectory
location ^~ /microblog {
    alias html/microblog;
    try_files $uri $uri/ /microblog/index.html;
}

location /static {
    root html/microblog/static;
    expires 1y;
    add_header Cache-Control "public";
}

# -------------------------------

location /api {
    proxy_pass http://localhost:5000;
}

# ---------- DJANGO ------------

location /django {
    proxy_pass http://localhost:8000;
}

location /djangostatic {
    expires 1y;
    add_header Cache-Control "public";
}

location /media {
    #root /Users/Shared/src/django_src/alex_django_db/media;
    expires 1y;
    add_header Cache-Control "public";
}

# -------------------------------

location /alexgram {
    proxy_pass http://localhost:8001;
}

location /flask {
    proxy_pass http://localhost:5001;
}

location /guyton {
    proxy_pass http://localhost:5002/calculator;
}

# ---------- NEXT ----------------

location /next {
    proxy_pass http://localhost:3000;
}

#location /nextbuild {
    #root /Users/Shared/src/react_src/nextjs;
#}

#location /_next/static {
    #root /Users/Shared/src/react_src/nextjs/nextbuild;
    #proxy_pass http://localhost:3000/_next/static;
    #proxy_pass http://localhost:8016/_next/static;
#}

#location /_next/image {
    #proxy_pass http://localhost:8016/_next/image;
#}

#------- IGAMING PLATFORM ------------

#location /monorepo {
    #proxy_pass http://localhost:8013;
    #proxy_set_header Host $host;
    #proxy_set_header X-Real-IP $remote_addr;
    #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #proxy_set_header X-Forwarded-Proto $scheme;
#}

#location / {
    #proxy_pass http://localhost:8016/;
#}

#location /icons {
    #proxy_pass http://localhost:8016/icons;
#}

# -------- ROOT -------------------

location / {
    root   html;
    index  index.html index.htm;
}